version: '3'

services:
  peerprep-client:
    image: client:peerprep
    container_name: peerprep-client
    build:
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app # Mount the client source code directory as a volume
      - /usr/src/app/node_modules # Mount the node_modules ONLY IN CONTAINER
    networks:
      - peerprep-network

  peerprep-question-api:
    image: question-api:peerprep
    container_name: peerprep-question-api
    build:
      context: ./question-api
    ports:
      - '8000:8000'
    logging:
      driver: json-file
    volumes:
      - ./question-api:/usr/src/app # Mount the Server source code directory as a volume
      - /usr/src/app/node_modules # Mount the node_modules ONLY IN CONTAINER
    networks:
      - peerprep-network
    depends_on:
      - peerprep-mongo

  peerprep-mongo:
    image: mongo:latest
    container_name: peerprep-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - peerprep-network

  peerprep-nginx:
    image: nginx:latest
    container_name: peerprep-nginx
    ports:
      - '80:80' # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount the Nginx configuration file
    networks:
      - peerprep-network
    depends_on:
      - peerprep-client # Wait until Client app container is up
      - peerprep-question-api # Wait until Server app container is up

networks:
  peerprep-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
